[build-system]
requires = ["numpy", "pandas", "setuptools", "cython", "biopython", "reportlab"]
build-backend = "setuptools.build_meta"

[tools.setuptools]
license-file = []

[project]
dependencies = [
  "numpy",
  "pandas",
  "cython",
  "biopython",
  "reportlab"
]