name: Build Wheels and Publish to PyPI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Install cibuildwheel
      - name: Install cibuildwheel
        run: pip install cibuildwheel twine

      # Step 3: Build wheels with manylinux2014
      - name: Build wheels
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_SKIP: "pp*"
          CIBW_BEFORE_BUILD: |
            yum install -y libjpeg-devel zlib-devel gcc gcc-c++ libffi-devel python3-devel
            if [[ "${CIBW_PYTHON_IMPLEMENTATION}" == "pypy" ]]; then
              pip install --upgrade "setuptools<72.2.0";
            fi
            pip install --upgrade pip wheel
        run: cibuildwheel --platform linux

      # Step 4: Upload wheels to PyPI
      - name: Publish to PyPI
        if: github.ref == 'refs/heads/master'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload wheelhouse/*
