name: Build Wheels and Publish to PyPI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Install cibuildwheel
      - name: Install cibuildwheel
        run: pip install cibuildwheel twine

      # Step 3: Debug environment variables
      - name: Debug Environment Variables
        run: |
          echo "CIBW_SKIP=$CIBW_SKIP"
          echo "CIBW_MUSLLINUX_IMAGE=$CIBW_MUSLLINUX_IMAGE"

      # Step 4: Build wheels with manylinux2014
      - name: Build wheels
        env:
          CIBW_ARCHS: x86_64  # Only build for 64-bit architecture
          CIBW_MUSLLINUX_IMAGE: ""  # Disable musllinux builds
          CIBW_SKIP: "musllinux* pp*"  # Skip musllinux and PyPy builds
          CIBW_BEFORE_BUILD: |
            yum install -y libjpeg-devel zlib-devel gcc gcc-c++ libffi-devel python3-devel
            pip install --upgrade pip setuptools wheel
        run: cibuildwheel --platform linux

      # Step 5: Upload wheels to PyPI
      - name: Publish to PyPI
        if: github.ref == 'refs/heads/master'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload wheelhouse/*
