name: Build Wheels

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # cibuildwheel will handle other versions

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels
        run: cibuildwheel --platform linux

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/
          
      - name: Publish to PyPI
        if: github.ref == 'refs/heads/master'  # Only deploy on pushes to master
        run: |
          python -m pip install twine
          twine upload --non-interactive --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} wheelhouse/*
